"""
Auto GitHub Issues Creator

Automatically creates GitHub issues for CRITICAL and HIGH severity vulnerabilities
Includes remediation steps, priority labels, and AI-generated fix suggestions
"""

import json
import os
import sys
import requests
from datetime import datetime

def create_github_issue(repo, token, title, body, labels):
    """Create a GitHub issue"""
    url = f"https://api.github.com/repos/{repo}/issues"
    
    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json'
    }
    
    data = {
        'title': title,
        'body': body,
        'labels': labels
    }
    
    try:
        response = requests.post(url, headers=headers, json=data, timeout=10)
        
        if response.status_code == 201:
            issue_url = response.json()['html_url']
            return True, issue_url
        else:
            return False, f"API Error: {response.status_code} - {response.text}"
    
    except Exception as e:
        return False, str(e)

def load_trend_report():
    """Load the latest AI trend report"""
    try:
        with open('ai-trend-report.json', 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print("⚠️ No trend report found. Run ai_trend_intelligence.py first.")
        return None
    except Exception as e:
        print(f"❌ Error loading report: {e}")
        return None

def check_existing_issues(repo, token, cve_id):
    """Check if issue already exists for this CVE"""
    url = f"https://api.github.com/repos/{repo}/issues"
    
    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json'
    }
    
    params = {
        'state': 'open',
        'labels': 'security,ai-generated'
    }
    
    try:
        response = requests.get(url, headers=headers, params=params, timeout=10)
        
        if response.status_code == 200:
            issues = response.json()
            for issue in issues:
                if cve_id in issue['title']:
                    return True
        
        return False
    
    except Exception as e:
        print(f"⚠️ Error checking existing issues: {e}")
        return False

def format_issue_body(issue, risk_score):
    """Format issue body with remediation steps"""
    
    cve_id = issue.get('cve_id', 'Unknown')
    package = issue.get('package', 'Unknown')
    title = issue.get('title', 'Security vulnerability')
    fixed_version = issue.get('fixed_version', 'Unknown')
    days_present = issue.get('days_present', 0)
    first_seen = issue.get('first_seen', 'Unknown')
    last_seen = issue.get('last_seen', 'Unknown')
    
    # Calculate risk impact
    risk_impact = 10 if days_present > 14 else 5
    
    body = f"""
## 🚨 AI-Detected Security Issue

**Severity:** CRITICAL  
**Risk Score Impact:** +{risk_impact} points  
**Age:** {days_present} days (First seen: {first_seen})  
**Status:** ⚠️ Persistent issue - appears in multiple scans

---

### 📋 Issue Details

**CVE ID:** {cve_id}  
**Package:** `{package}`  
**Title:** {title}  
**Fixed Version:** `{fixed_version}`

**Detection History:**
- First detected: {first_seen}
- Last detected: {last_seen}
- Scans affected: {days_present} consecutive scans

---

### 💡 Remediation Steps

#### Option 1: Update Dependency (Recommended)

Update `pom.xml`:

```xml
<dependency>
  <groupId>org.example</groupId>
  <artifactId>{package}</artifactId>
  <version>{fixed_version}</version>
</dependency>
```

Then run:
```bash
mvn clean install
mvn test
```

#### Option 2: Exclude Vulnerable Dependency

If direct update isn't possible:

```xml
<dependency>
  <groupId>parent-package</groupId>
  <artifactId>parent-artifact</artifactId>
  <version>1.0.0</version>
  <exclusions>
    <exclusion>
      <groupId>org.example</groupId>
      <artifactId>{package}</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

---

### 🎯 Priority Justification

This issue is marked as **HIGH PRIORITY** because:
- ✅ CRITICAL severity level
- ✅ Present for {days_present} days (aging issue)
- ✅ Appears in multiple consecutive scans
- ✅ Fix is available: `{fixed_version}`

**Estimated Fix Time:** 15-30 minutes  
**Risk Reduction:** -{risk_impact} points from Risk Score

---

### 🔗 References

- [CVE Details](https://nvd.nist.gov/vuln/detail/{cve_id})
- [Package Documentation](https://search.maven.org/artifact/{package})

---

### ✅ Verification Steps

After applying the fix:

1. Run security scan: `mvn verify`
2. Check Trivy scan: `trivy fs .`
3. Verify in next CI/CD run
4. Confirm issue no longer appears in reports

---

**🤖 Auto-generated by AI Security Intelligence**  
**Run ID:** Latest scan  
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}

---

### 📊 Impact on Security Posture

Fixing this issue will:
- Reduce Risk Score by approximately {risk_impact} points
- Eliminate CRITICAL vulnerability from codebase
- Improve overall security posture

**Current Risk Score:** {risk_score}/100  
**Projected Score After Fix:** {max(0, risk_score - risk_impact)}/100
"""
    
    return body

def main():
    print("🤖 Auto GitHub Issues Creator")
    print("=" * 60)
    
    # Get GitHub credentials
    github_token = os.getenv('GITHUB_TOKEN')
    github_repo = os.getenv('GITHUB_REPOSITORY')
    
    if not github_token:
        print("❌ Error: GITHUB_TOKEN not set")
        sys.exit(1)
    
    if not github_repo:
        print("❌ Error: GITHUB_REPOSITORY not set")
        print("   Should be in format: owner/repo")
        sys.exit(1)
    
    print(f"📦 Repository: {github_repo}")
    
    # Load trend report
    print("📊 Loading trend analysis report...")
    report = load_trend_report()
    
    if not report:
        print("❌ No report data available")
        sys.exit(1)
    
    critical_issues = report.get('persistent_critical_issues', [])
    risk_score = report.get('risk_score', 0)
    
    if not critical_issues:
        print("✅ No persistent critical issues found - no issues to create")
        return
    
    print(f"\n🔍 Found {len(critical_issues)} persistent critical issues")
    print("📝 Creating GitHub issues...\n")
    
    created_count = 0
    skipped_count = 0
    
    for issue in critical_issues[:5]:  # Limit to top 5
        cve_id = issue.get('cve_id', 'Unknown')
        package = issue.get('package', 'Unknown')
        
        # Check if issue already exists
        if check_existing_issues(github_repo, github_token, cve_id):
            print(f"⏭️  Skipped: {cve_id} (issue already exists)")
            skipped_count += 1
            continue
        
        # Create issue
        title = f"[SECURITY] CRITICAL: {cve_id} in {package}"
        body = format_issue_body(issue, risk_score)
        labels = ['security', 'critical', 'ai-generated', 'vulnerability']
        
        success, result = create_github_issue(github_repo, github_token, title, body, labels)
        
        if success:
            print(f"✅ Created: {cve_id}")
            print(f"   URL: {result}")
            created_count += 1
        else:
            print(f"❌ Failed: {cve_id}")
            print(f"   Error: {result}")
    
    print("\n" + "=" * 60)
    print(f"📊 Summary:")
    print(f"   ✅ Created: {created_count} issues")
    print(f"   ⏭️  Skipped: {skipped_count} issues (already exist)")
    print(f"   📝 Total processed: {len(critical_issues[:5])} issues")
    
    if created_count > 0:
        print(f"\n🔗 View issues: https://github.com/{github_repo}/issues?q=is:issue+is:open+label:ai-generated")

if __name__ == "__main__":
    main()
